In [1]:
import pandas as pd

# Load and display the first few rows of each dataset to understand its structure
dataset1 = pd.read_excel('C:\\Users\\PC2\\Downloads\\Ver04\\TFND_2019_Ver01.xlsx')
dataset2 = pd.read_excel('C:\\Users\\PC2\\Downloads\\output.xlsx')

In [2]:
dataset1.head()

,dID,NewsSite(Trigger),Year,Month,Day,Class,MainSource,Source,MainCategory,Category,DocumentIdentifier
0,1,MAINSTREAM_MEDIA,2017,1,1,TRUE,GDELT,AA,WORLD,6,http://aa.com.tr/tr/dunya/abd-disisleri-bakanl...
1,2,MAINSTREAM_MEDIA,2017,1,1,TRUE,GDELT,AA,WORLD,2,http://aa.com.tr/tr/dunya/almanya-basbakani-me...
2,3,MAINSTREAM_MEDIA,2017,1,1,TRUE,GDELT,AA,WORLD,2,http://aa.com.tr/tr/dunya/almanyaya-2017de-sec...
3,4,MAINSTREAM_MEDIA,2017,1,1,TRUE,GDELT,AA,WORLD,2,http://aa.com.tr/tr/dunya/brezilyada-yeni-yil-...
4,5,MAINSTREAM_MEDIA,2017,1,1,FAKE,GDELT/MVN,AA,WORLD,2,PopularNewsSites (More than once)

In [3]:
dataset2.head()

,Unnamed: 0,dID,FileName,Orj_Text,Orj_WordCount,Zem_Text,Zem_WordCount,SpellErrorCount,HotWordsCount,StopWordsCount,SentencesCount,LongWordsCount,ComplexityScore,Orj_Text_processed,Orj_Text_processed_stemmed,Orj_Text_sentiment
0,0,1,000001_Text_of_URL.txt,"ABD Dışişleri Bakanlığı Sözcüsü Toner, ""NATO m...",119,"abd Dışişleri bakan sözcü Toner, ""NATO müttefi...",97.0,NaN,NaN,NaN,NaN,NaN,NaN,abd dışişleri bakanlığı sözcüsü toner nato müt...,abd dışişleri bakanlığı sözcüsü toner nato müt...,Neutral
1,1,2,000002_Text_of_URL.txt,"Almanya Başbakanı Merkel, İstanbul'daki terör ...",201,"almanya başbakan Merkel, istanbul terör saldır...",152.0,NaN,NaN,NaN,NaN,NaN,NaN,almanya başbakanı merkel terör saldırısına ili...,almanya başbakanı merkel terör saldırısına ili...,Neutral
2,2,3,000003_Text_of_URL.txt,"BERLİN\nGeçen yılı terör korkusu, cumhurbaşkan...",443,BERLİN. \ngeçen yıl terör korku cumhurbaşkanlı...,351.0,NaN,NaN,NaN,NaN,NaN,NaN,geçen yılı terör korkusu cumhurbaşkanlığı seçi...,geçen yılı terör korkusu cumhurbaşkanlığı seçi...,Neutral
3,3,4,000004_Text_of_URL.txt,"SAO PAULO\nBrezilya'da, yeni yıl gecesi eski e...",144,SAO PAULO. \nbrezilya yeni yıl gece eski eşin ...,108.0,NaN,NaN,NaN,NaN,NaN,NaN,sao paulo yeni yıl gecesi eski eşinin evini ba...,sao paulo yeni yıl gecesi eski eşinin evini ba...,Neutral
4,4,5,000005_Text_of_URL.txt,"ABD'nin ""suç başkenti"" olarak nitelenen Chicag...",153,abd suç başkent ol nitele Chicago'da 2016 yıl ...,133.0,NaN,NaN,NaN,NaN,NaN,NaN,suç başkenti olarak nitelenen 2016 yılında mey...,suç başkenti olarak nitelenen 2016 yılında mey...,Neutral

In [4]:
# Merge the datasets on 'dID' column
merged_data = pd.merge(dataset1, dataset2, on='dID', how='inner')

# Selecting relevant features and the label
features_and_label = merged_data[[
    'Zem_WordCount','MainSource',
     'Orj_Text_sentiment','Orj_WordCount', 'Class'
]]

# Display the first few rows of the merged and selected data
features_and_label.head()

   Zem_WordCount MainSource Orj_Text_sentiment Orj_WordCount Class
0           97.0      GDELT            Neutral           119  TRUE
1          152.0      GDELT            Neutral           201  TRUE
2          351.0      GDELT            Neutral           443  TRUE
3          108.0      GDELT            Neutral           144  TRUE
4          133.0  GDELT/MVN            Neutral           153  FAKE

In [5]:
features_and_label.isna().sum()

Zem_WordCount         184
MainSource              0
Orj_Text_sentiment      0
Orj_WordCount          41
Class                   0
dtype: int64

In [6]:
features_and_label.dropna(inplace=True)
features_and_label.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98884 entries, 0 to 98898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Zem_WordCount       98884 non-null  float64
 1   MainSource          98884 non-null  object
 2   Orj_Text_sentiment  98884 non-null  object
 3   Orj_WordCount       98884 non-null  object
 4   Class               98884 non-null  object
dtypes: float64(1), object(4)
memory usage: 4.5+ MB

C:\Users\PC2\AppData\Local\Temp\ipykernel_33160\2475016949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_and_label.dropna(inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder

le_source = LabelEncoder()
features_and_label['MainSource'] = le_source.fit_transform(features_and_label['MainSource'])

# Encoding categorical data
le_sentiment = LabelEncoder()
features_and_label['Orj_Text_sentiment_encoded'] = le_sentiment.fit_transform(features_and_label['Orj_Text_sentiment'])

# Encoding the Class label
le_class = LabelEncoder()
# change true to True inn (features_and_label['Class']
features_and_label['Class'] = features_and_label['Class'].apply(lambda x: 'TRUE' if x == True else x)
features_and_label['Class_encoded'] = le_class.fit_transform(features_and_label['Class'])

C:\Users\PC2\AppData\Local\Temp\ipykernel_33160\3146864290.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_and_label['MainSource'] = le_source.fit_transform(features_and_label['MainSource'])
C:\Users\PC2\AppData\Local\Temp\ipykernel_33160\3146864290.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_and_label['Orj_Text_sentiment_encoded'] = le_sentiment.fit_transform(features_and_label['Orj_Text_sentiment'])
C:\Users\PC2\AppData\Local\Temp\ipykernel_33160\3146864290.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_and_label['Class'] = features_and_label['Class'].apply(lambda x: 'TRUE' if x == True else x)
C:\Users\PC2\AppData\Local\Temp\ipykernel_33160\3146864290.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_and_label['Class_encoded'] = le_class.fit_transform(features_and_label['Class'])

In [8]:
# remove class_encoded 2 and 4 from the feature_label
features_and_label = features_and_label[features_and_label['Class_encoded'] != 2]
features_and_label = features_and_label[features_and_label['Class_encoded'] != 4]

features_and_label['Class_encoded'].value_counts()

Class_encoded
3    98424
0      424
1       35
Name: count, dtype: int64

In [9]:
final_features = features_and_label.drop(columns=['Orj_Text_sentiment', 'Class'])
final_label = features_and_label['Class_encoded']
final_features.head()

,Zem_WordCount,MainSource,Orj_WordCount,Orj_Text_sentiment_encoded,Class_encoded
0,97.0,1,119,1,3
1,152.0,1,201,1,3
2,351.0,1,443,1,3
3,108.0,1,144,1,3
4,133.0,2,153,1,0

In [10]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, train_test_split

# Initialize the Support Vector Classifier
svc = SVC(random_state=42)

# Define the parameter grid for hyperparameter tuning of SVM
param_grid = {
    'C': [0.1, 1, 10, 100],  # Regularization parameter
}

# Remove the 'Class_encoded' feature from the feature set
features_final = final_features.drop(columns=['Class_encoded'])

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    features_final, final_label, test_size=0.2, random_state=42
)

# Set up the grid search with cross-validation for the SVM model
grid_search = GridSearchCV(svc, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters, best cross-validation score, and evaluate on the test set
best_params = grid_search.best_params_
best_score = grid_search.best_score_
best_model = grid_search.best_estimator_
test_accuracy = best_model.score(X_test, y_test)

(best_params, best_score, test_accuracy)

({'C': 0.1}, 0.995423862130445, 0.9950953127370178)